#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Feb 10 19:52:56 2023

@author: katarina
"""

#%% U1 
import numpy as np
s1=0; s2=0.1
for k in range(1,10001,2):
    s1=s1+abs(np.sin(0.1*k))/k
    s2=s2+np.cos(0.1*k)/k**2
    if s1<=s2:
        print(k)


#%% U2 
def count(vec):
    leng=[1]
    j=0
    for i in range(1,len(vec)):
        if vec[i-1]==vec[i]:
            leng[j]=leng[j]+1
        else:
            j=j+1
            leng=leng+[1]
    return leng


#%% U3 
import numpy as np
def is_stoch(M):
    (m,n)=np.shape(M)
    if m!=n: return False
    if np.any(M<0): return False
    for i in range(m):
        if sum(M[i])!=1 or sum(M.T[i])!=1:
            return False
    return True
#%% U4 
import matplotlib.pyplot as plt
import numpy as np
fig, ax = plt.subplots(subplot_kw={"projection": "3d"})
x=np.linspace(-2,2); y=np.linspace(-2,2)
X, Y = np.meshgrid(x,y)
for i in range(5):
    Z=X+Y-i
    ax.plot_surface(X,Y,-Z)
    
#%% U5 
import os
def comp_data():
    l=os.listdir()
    S=[]
    for f in l:
        if f.endswith(".dat"):
            with open(f,'r') as fid:
                num=fid.readlines()
                s=0
                for i in range(len(num)):
                    s=s+float(num[i])
                S.append(s/len(num))
    return S

#%% U6 
from sympy import isprime
def primepair():
    par=[(3,5)]
    n=5
    while len(par)<10:
        n=n+2
        if isprime(n-2) and isprime(n):
            s1=0; s2=0
            num_str=str(n-2)
            for char in num_str:
               s1 += int(char)
            num_str=str(n)
            for char in num_str:
                s2 += int(char)
            if s1>s2:
                par.append((n-2,n))
    return par
print(primepair())
            









